language: go

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -y
  - sudo apt-get upgrade
  - sudo apt-get install -y glide

script:
    - make
    - make build
