language: go

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  # - sudo apt-get update
  # - sudo apt-get upgrade
  - sudo apt-get install glide -y

script:
    - make
    - make build
